# Resampling Methods for Model Selection and Evaluation


## Overview of Unit

**Learning Objectives**

* Bias vs. variance wrt model performance estimates
  * How is this different from bias vs. variable of model itself
* How to do parallel processing
* Types of resampling
  * Validation set approach
  * Leave One Out CV
  * K-Fold and Repeated K-Fold
  * Grouped K-Fold
  * Bootstrap resampling
* Use of resampling for tuning hyperparameters  
* Combining these resampling approaches with a Test set
  * Used for simultaneous model selection and evaluation
  * Single independent test set
  * Advanced topic: Nested resampling

**Readings**

* @APM [Chapter 4, pp 61 - 80](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)

* **Supplemental:** * @ISL [Chapter 5, pp 197 - 208 186](https://dionysus.psych.wisc.edu/iaml/pdfs/ISLRv2.pdf)


**Lecture Videos**

* [Lecture 1: Overview & Parallel Processing]() ~ 12 mins
* [Lecture 2: Single Validation/Test Set Approach]() ~ 13 mins
* [Lecture 3: Leave One Out Cross Validation]() ~ 9 mins
* [Lecture 4: K-fold Cross Validation Approaches]() ~ 18 mins
* [Lecture 5: Bootstrap Resampling]() ~ 10 mins
* [Lecture 6: Tuning Hyperparameters via Resampling]() ~ 17 mins
* [Lecture 7: Resampling for Both Model Selection and Evaluation]() ~ 14 mins
* [Lecture 8: Nested Resampling]() ~ 14 mins
* [Discussion]()

Post questions or discuss readings or lectures on Slack

**Application Assignment**
  
* [data](homework/unit_5/smoking_ema.csv)
* [data dictionary](homework/unit_5/data_dictionary.csv)
* [rmd shell](homework/unit_5/hw_unit_5_resampling.Rmd)
* [solution](homework/unit_5/key_unit_5_resampling.html) 


Post questions to application_assignments Slack channel

Submit the application assignment [here]() and complete the [unit quiz]() by 8 pm on Wednesday, February 21st

