# Midterm Exam

## Applications (take-home) Exam
The Applications exam is due at 8 pm on Wednesday, March 6th.

As the name suggests, it will focus primarily applications.   However, within the QMD file there are questions that also assess your understanding of what you are doing and why.

You should complete the exam as you have previously completed the application assignments:  

  - Download the datasets and rmd file below
  - Provide the requested code in the empty code chunks that are included in the rmd file
  - Answer the questions posed outside the code chunks within the text sections of the rmd file, immediately after the question.
  - When you are done, knit the file to html and upload this knit file through the Canvas
  - The exam is due on Wednesday, March 6th, at 8pm

In contrast to the application assignments, the TAs and I will not be able to answer substantive questions about the exam.  However, if you need us to clarify what we are requesting you to do for any specific question or believe you have found an error in the exam, please post your question to the exam_quizzes channel in Slack and we will respond ASAP


[Exam qmd shell](https://dionysus.psych.wisc.edu/iaml/midterm/midterm.qmd)

Data:

- [dataset 1](https://dionysus.psych.wisc.edu/iaml/midterm/data_1.csv); [data dictionary](https://dionysus.psych.wisc.edu/iaml/midterm/data_1_dictionary.docx)
- [dataset 2](https://dionysus.psych.wisc.edu/iaml/midterm/data_2.csv)
- [dataset 3](https://dionysus.psych.wisc.edu/iaml/midterm/data_3.csv)


## Conceptual Exam
The conceptual exam will be held in class during the Discussion section on Thursday, March 7th.
