# Advanced Performance Metrics


## Overview of Unit

**Learning Objectives**

* Understand costs and benefits of accuracy 
* Use of a confusion matrix
* Understand costs and benefits of other performanc metrics
* The ROC curve and area under the curve
* Model selection using other performance metrics
* How to address class imbalance
  * Selection of performance metric
  * Selection of classification threshold
  * Sampling and resampling approaches


**Readings**

* @APM [Chapter 11, pp 247-266](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)
* @APM [Chapter 16, pp 419-435](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)

**Lecture Videos**

* [Lecture 1: Unit Introduction]()
* [Lecture 2: The Confusion Matrix]()
* [Lecture 3: Metrics from the Confusion Matrix, Part 1]()
* [Lecture 4: Metrics from the Confusion Matrix, Part 2]()
* [Lecture 5: The Receiver Operating Characteristic (ROC) Curve]()
* [Lecture 6: Selecting Model Configurations with Other Metrics]()
* [Lecture 7: Addressing Class Imbalance]()

* [Discussion]()

**Coding Assignment**

* [data]()
* [rmd shell]()
* solution: [rmd](); [html]()


Submit the application assignment [here](https://canvas.wisc.edu/courses/395546/assignments/2187692) and complete the [unit quiz](https://canvas.wisc.edu/courses/395546/quizzes/514050) by 8 pm on Wednesday, March 13th
 

