# Model Comparisons and Other Explanatory Goals


## Overview of Unit

**Learning Objectives**

* Use of the permutation test to evaluate overall model performance
  * Using test performance
  * Using resampled performance
  
* Use of model comparisons to compare models
  * Feature ablation
  * Frequentist correlated t-test using CV
  * Bayesian estimation for model comparisons
    * ROPE

* Variable important metrics for explanation
  * Permutation feature importance
  * Shapley values
    * local importance
    * global importance

* Visual approaches for explanation
  * Partial dependence plots
  * Accumulated Local Effects (ALE) plots
  
**Readings**

* @Benavoli2017 [paper](pdfs/benavoli_2017_bayesian_t_test.pdf):  Read pages 1-9 that describe the correlated t-test and its limitations.
* @Kruschke2018 [paper](pdfs/kruschke2018a.pdf): Describes Bayesian estimation and the ROPE (generally, not in the context of machine learning and model comparisons)
* @IML [Chapter 3 - Interpretability](https://christophm.github.io/interpretable-ml-book/interpretability.html)
* @IML [Chapter 6 - Model-Agnostic Methods](https://christophm.github.io/interpretable-ml-book/agnostic.html)
* @IML [Chapter 8 - Global Model Agnostic Methods](https://christophm.github.io/interpretable-ml-book/global-methods.html): Read setions 8.1, 8.2, 8.3, and 8.5
* @IML [Chapter 9 - Local Model-Agnostic Methods](https://christophm.github.io/interpretable-ml-book/shapley.html): Read section 9.5

**Lecture Videos**

* [Introduction to the Permutation Test]()
* [Permutation Test with Single Held-Out Test set]()
* [Permutation Test with Resampling for Selection and Evaluation]()
* [Introduction to Model Comparisons]()
* [The Nadeau & Bengio Correlated t-test for Model Comparisons]()
* [Bayesian Estimation for Model Comparisons]()
* [Feature Importance Metrics to Understand Models]()
* [Visual Approaches to Understand Models]()
* [Exploring Interactions]()

* [Discussion]()


**Application Assignment**

* data: [admissions.csv](homework/unit_9/admissions.csv)
* [assignment rmd](homework/unit_9/hw_unit_9_explanatory.Rmd)
* solution html: [rmd](); [html]()

Post questions to the application_assignments Slack channel

Submit the application assignment [here](https://canvas.wisc.edu/courses/395546/assignments/2187693) and complete the[unit quiz](https://canvas.wisc.edu/courses/395546/quizzes/514055) by 8 pm on Wednesday, April 10th 

