# Advanced Models: Neural Networks


## Overview of Unit

**Learning Objectives**

* What are neural networks
* Types of neural networks
* Neural network architecture
  * layers and units
  * weights and biases
  * activation functions
  * cost functions
  * optimization
    * epochs
    * batches
    * learning rate
* How to fit 3 layer MLPs in tidymodels using Keras

**Readings**

* [Neural Networks and Deep Learning, Chapter 1: Using neural networks to recognize handwritten digits](http://neuralnetworksanddeeplearning.com/chap1.html)

**Lecture Videos**

* [Lecture 1: But what is a Neural Network?]()
* [Lecture 2: Gradient descent, how neural networks learn]()
* [Lecture 3: What is backpropagation really doing?]()
* [Optional Lecture 4: Backpropagation calculus]()
* [Lecture 5: Introduction and the MNIST dataset]()
* [Lecture 6: Fitting neural networks in tidymodels with Keras - Part 1]()
* [Lecture 7: Fitting neural networks in tidymodels with Keras - Part 2]()
* [Lecture 8: Addressing overfitting]()
* [Lecture 9: Selecting model configurations and final remarks]()

* [Discussion]()

**Coding Assignment**

* wine quality datasets:  [training](homework/unit_11/wine_quality_trn.csv);[test](homework/unit_11/wine_quality_test.csv)
* [rmd shell](homework/unit_11/hw_unit_11_neural_nets.Rmd)
* solution: [rmd](); [html]()


 Submit the application assignment [here]() and complete the [unit quiz]() by 8 pm on Wednesday, April 10th
 

