# Natural Language Processing: Text Processing and Feature Engineering


## Overview of Unit

**Learning Objectives**

* Objective 1
* Objective 2


**Readings**

* @SMLTAR [Chapter 2: Tokenization](https://smltar.com/tokenization.html)
* @SMLTAR [Chapter 5: Word Embeddings](https://smltar.com/embeddings.html)

NOTES: Please read the above chapters more with an eye toward concepts and issues 
rather than code.  I will demonstrate a minimum set of functions to accomplish
the NLP modeling tasks for this unit.

Also know that the entire @SMLTAR [book] is really mandatory reading.  I would also 
strongly recommend this entire @TMR [book](https://www.tidytextmining.com/).  Both 
will be important references at a minimum.


**Lecture Videos**

* [Lecture 1: General Text (Pre-) Processing - the stringr package]()
* [Lecture 2: General Text (Pre-) Processing - regular expressions]()
* [Lecture 3: The IMDB Reviews Dataset]()
* [Lecture 4: Tokenization- Part 1]()
* [Lecture 5: Tokenization- Part 2]()
* [Lecture 6: Stopwords]()
* [Lecture 7: Stemming]()
* [Lecture 8: Bag of Words]()
* [Lecture 9: NLP in Action - Part 1]()
* [Lecture 10: NLP in Action - Part 2]()


**Coding Assignment**

* [data](homework/unit_12/alcohol_tweets.csv)
* [rmd shell](homework/unit_12/hw_unit_12_nlp.Rmd)
* [GloVE embeddings](homework/unit_12/glove_twitter.csv)
* solution: [rmd](); [html]()


 Submit the application assignment [here]() and complete the [unit quiz]() by 8 pm on Wednesday, April 17th
 
