# Applications for Machine Learning: Synthesis and Concept Generalization


## Overview of Unit

**Learning Objectives**

This week we will read a short "book" by Andrew Ng, a very well known computer scientist in the field of AI who also offers one of the best known MOOCs on machine learning at [Coursera](https://www.coursera.org/learn/machine-learning)

This book is very application oriented and practical. The goals for reading it are:

1. To encourage generalization of your learning - some terminology and perspectives will be different here from the authors you have been reading.  The concepts are all the same.  We hope that seeing these ideas in a new context will help you recognize and generalize them.

2. The book is applied.  It will help you consider carefully how to make best use of your data for model selection, evaluation, error analysis and other related tasks to figure out what to do when your models don't perform well.

3. It is a "course in a book", such that we hope this will encourage you to see the big picture of how all the pieces from our course fit together.

Finally, it is a quick read so don't worry that it is a full book.  Also, you have no lectures or application assigment this week.  It is all about consolidation now!!!!  You are in the home stretch.

**Readings**

* @MLY [pdf](pdfs/ng_machine_learning_yearning.pdf)


**Lecture Videos**

No lectures this week.  Only lab and discussion section.

**Application Assignment**

No assignment this week!


 The [unit quiz]() is due by 8 pm on Wednesday, April 24th 
 
 
