# title: "Introduction to Applied Machine Learning"
# author: John J. Curtin, PhD
toc: false
bibliography: refs.bib
css: slides.css
format: 
  revealjs:
    scrollable: true
    chalkboard: true
callout-icon: false
execute:
  echo: true
