---
output: html_document
editor_options:
  chunk_output_type: console
---

# Machine learning/AI in the media { .unnumbered}

## 2026

- [Launching the Genesis Mission](https://urldefense.com/v3/__https://www.whitehouse.gov/presidential-actions/2025/11/launching-the-genesis-mission/__;!!Mak6IKo!KLR6aRwSglF-00cVxw1DXJO8-dWCmwT7iXzuK6TAKBQsXVM1nm9-Pj95A_iV9qkqvheZNxfPQg0eU8zRng$).  But also see: [Genetic Data From Over 20,000 U.S. Children Misused for ‘Race Science’ (NYT)](https://www.nytimes.com/2026/01/24/us/children-genetics-race-science.html?unlocked_article_code=1.HFA.ZL74.fGI5aFlPpb2s&smid=url-share)

- [A.I. Could Solve Some of Humanity’s Hardest Problems. It Already Has. (Ezra Klein show)](https://www.nytimes.com/2023/07/11/opinion/ezra-klein-podcast-demis-hassabis.html?smid=nytcore-ios-share): Demis Hassabis, the chief executive of DeepMind, discusses how A.I. systems can accelerate scientific research.

- [Where Is All the A.I.-Driven Scientific Progress? (Hard Fork)](https://pca.st/episode/58aa229d-ca4f-4cb0-8908-60d9551b18c1): The leaders of the biggest A.I. labs argue that artificial intelligence will usher in a new era of scientific discovery, which will help us cure diseases and accelerate our ability to address the climate crisis. But what has A.I. actually done for science so far?  To understand, we asked Sam Rodriques, a scientist turned technologist who is developing A.I. tools for scientific research through his nonprofit FutureHouse and a for-profit spinoff, Edison Scientific. Edison recently released Kosmos — an A.I. agent, or A.I. scientist to use the company’s language, that it says can accomplish six months of doctoral or postdoctoral-level research in a single 12-hour run.  Sam walks us through how Kosmos works, and why tools like it could dramatically speed up data analysis. But he also discusses why some of the most audacious claims about A.I. curing disease are unrealistic, as well as what bottlenecks still stand in the way of a true A.I.-accelerated future.

- [The Quest for A.I. ‘Scientific Superintelligence’ (NYT)](https://www.nytimes.com/2025/03/10/technology/ai-science-lab-lila.html): An ambitious start-up embodies new optimism that artificial intelligence can turbocharge scientific discovery

- [How AI is saving billions of years of human research time (TED)](https://www.ted.com/talks/max_jaderberg_how_ai_is_saving_billions_of_years_of_human_research_time): Can AI compress the yearslong research time of a PhD into seconds? Research scientist Max Jaderberg explores how “AI analogs” simulate real-world lab work with staggering speed and scale, unlocking new insights on protein folding and drug discovery. Drawing on his experience working on Isomorphic Labs' and Google DeepMind's AlphaFold 3 — an AI model for predicting the structure of molecules — Jaderberg explains how this new technology frees up researchers' time and resources to better understand the real, messy world and tackle the next frontiers of science, medicine and more.

- [A.I. Could Solve Some of Humanities Hardest Problems: It Already Has (Ezra Klein)](https://www.nytimes.com/2023/07/11/opinion/ezra-klein-podcast-demis-hassabis.html): Since the release of ChatGPT, huge amounts of attention and funding have been directed toward chatbots. These A.I. systems are trained on copious amounts of human-generated data and designed to predict the next word in a given sentence. They are hilarious and eerie and at times dangerous. But what if, instead of building A.I. systems that mimic humans, we built those systems to solve some of the most vexing problems facing humanity?

- [We Let AI Run Our Office Vending Machine. It Lost Hundreds of Dollars. (WSJ video)](https://www.wsj.com/video/series/joanna-stern-personal-technology/we-let-ai-run-a-vending-machine-it-stocked-a-live-fish-and-a-playstation/ECA7F3CD-BA6F-4F34-9D2E-2B94571A0C68): Anthropic’s Claude AI ran a vending machine at WSJ headquarters for several weeks. It lost hundreds of dollars, bought some crazy stuff and taught us a lot about the future of AI agents. WSJ’s Joanna Stern tested it all out.

- [Claude Is Taking the AI World by Storm, and Even Non-Nerds Are Blown Away (WSJ)](https://www.wsj.com/tech/ai/anthropic-claude-code-ai-7a46460e?st=gctU58&reflink=article_imessage_share): Anthropic’s Claude Opus 4.5, used within Claude Code, is being hailed by engineers and non-engineers for its advanced capabilities in software development and other tasks.

- [The Thinking Game (YouTube)](https://www.youtube.com/watch?v=b1EaXnCC4N8): A journey into the heart of DeepMind, a leading AI lab, as it strives to unravel the mysteries of artificial general intelligence (AGI). Inside DeepMind's London headquarters, founder Demis Hassabis and his team are relentlessly pursuing the creation of AI that matches or surpasses human abilities on a wide range of tasks.

- [Nobel Prize in Chemistry Goes to 3 Scientists for Predicting and Creating Proteins (NYT)](https://www.nytimes.com/2024/10/09/science/nobel-prize-chemistry.html?smid=nytcore-ios-share): The Nobel, awarded to David Baker of the University of Washington and Demis Hassabis and John M. Jumper of Google DeepMind, is the second this week to involve artificial intelligence.
