# Course Materials {.unnumbered}

## Unit 1: Overview

**Reading**

- @Yarkoni2017 [paper](pdfs/yarkoni_2017_choosing_prediction_over_explanation.pdf)
- @ISL [Chapter 2, pp 15 - 42](pdfs/isl_2.pdf)

**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/d01_overview.html)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d01/)

**Videos**

- [Lecture 1: An Introductory Framework](https://mediaspace.wisc.edu/media/iaml_1-1/1_pii1hb1q) ~ 9 mins
- [Lecture 2: More Details on Supervised Techniques](https://mediaspace.wisc.edu/media/iaml_1-2/1_5e1iz7aa) ~ 23 mins
- [Lecture 3: Key Terminology in Context](https://mediaspace.wisc.edu/media/iaml+1-3/1_3ebheuao) ~ 11 mins
- [Lecture 4: An Example of Bias-Variance Tradeoff](https://mediaspace.wisc.edu/media/iaml+1-4/1_ocn8pqi6) ~ 27 mins

- [Discussion - Tuesday](https://mediaspace.wisc.edu/media/iaml_discussion_2026_0120/1_re92j557)
- [Discussion - Thursday]()

**Lab Materials**

- None this week 


**Quiz**
- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692576) the unit quiz by 8 pm on Wednesday, January 21nd

**Application Assignment**

- No assignment this week

-----

## Unit 2: Exploratory Data Analysis

**Reading**

[NOTE: These are short chapters.  You are reading to understand the framework of visualizing data in R.  Don't feel like you have to memorize the details.  These are reference materials that you can turn back to when you need to write code!]

- @RDS [Chapter 1, Data Visualization](https://r4ds.hadley.nz/data-visualize)
- @RDS [Chapter 9, Layers](https://r4ds.hadley.nz/layers)
- @RDS [Chapter 10, Exploratory Data Analysis](https://r4ds.hadley.nz/EDA)

**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l02/)
- [Discussion](d02_exploratory_data_analysis.html)

**Videos**

- [Lecture 1: Stages of Data Analysis and Model Development](https://mediaspace.wisc.edu/media/iaml+2-1/1_m7rm2anw) ~ 10 mins
- [Lecture 2: Best Practices and Other Recommendations](https://mediaspace.wisc.edu/media/iaml+2-2/1_nxtr5uda) ~ 27 mins
- [Lecture 3: EDA for Data Cleaning](https://mediaspace.wisc.edu/media/iaml+2-3/1_xorv88kj) ~ 41 mins
- [Lecture 4: EDA for Modeling - Univariate](https://mediaspace.wisc.edu/media/iaml+2-4/1_f6hm842y) ~ 24 mins
- [Lecture 5: EDA for Modeling - Bivariate](https://mediaspace.wisc.edu/media/iaml+2-5/1_y1gydyw4) ~ 20 mins
- [Lecture 6: Working with Recipes](https://mediaspace.wisc.edu/media/iaml+2-6/1_rf4pbef3) ~ 13 mins

- [Discussion](https://mediaspace.wisc.edu/media/iaml+2026_0129/1_zp0bxauh)
- [Lab](https://mediaspace.wisc.edu/media/Unit+2+Lab+1+27+2026/1_w8qjgmbz)


**Lab Materials**

- [Lab 2](lab/unit_02_ta.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692577) the unit quiz by 8 pm on Wednesday, January 28th.

**Application Assignment**

- [data](application_assignments/unit_02/ames_raw_class.csv)
- [data dictionary](application_assignments/unit_02/ames_data_dictionary.pdf)
- cleaning EDA:  [qmd](application_assignments/unit_02/hw_unit_02_cleaning.qmd) 
- modeling EDA: [qmd](application_assignments/unit_02/hw_unit_02_modeling.qmd)
- solutions:  [cleaning EDA](https://dionysus.psych.wisc.edu/iaml/key_unit_02_cleaning.html); [modeling EDA](https://dionysus.psych.wisc.edu/iaml/key_unit_02_modeling.html)

- [Submit](https://canvas.wisc.edu/courses/449429/assignments/2579945) the application assignment by 8 pm on Friday, January 30th.

-----

## Unit 3: Introduction to Regression Models 

**Reading**

- @ISL [Chapter 3, pp 59 - 109](pdfs/isl_2.pdf)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l03/)
- [Discussion](d03_regression.html)


**Videos**

- [Lecture 1: Overview](https://mediaspace.wisc.edu/media/iaml+unit+3-1/1_76q87xgn) ~ 13 mins
- [Lecture 2: The Simple Linear Model, Part 1](https://mediaspace.wisc.edu/media/iaml+unit+3-2/1_yyb8dcub) ~ 16 mins
- [Lecture 3: The Simple Linear Model, Part 2](https://mediaspace.wisc.edu/media/iaml+unit+3-3/1_ep9ibptc) ~ 12 mins 
- [Lecture 4: Extension to Multiple Predictors](https://mediaspace.wisc.edu/media/iaml+Unit+3-4/1_24rrga7b) ~ 15 mins
- [Lecture 5: Extension to Categorical Predictors](https://mediaspace.wisc.edu/media/iaml+unit+3-5/1_2a3tsj3n) ~ 30 mins
- [Lecture 6: Extension to Interactions and Non-Linear Effects](https://mediaspace.wisc.edu/media/iaml+unit+3-6/1_yo48m37z) ~ 11 mins
- [Lecture 7: Introduction to KNN](https://mediaspace.wisc.edu/media/iaml+unit+3-7/1_ega1aohm) ~ 9 mins
- [Lecture 8: The hyperparameter k](https://mediaspace.wisc.edu/media/iaml+unit+3-8/1_xc8x13en) ~ 13 mins
- [Lecture 9: Distance and Scaling in KNN](https://mediaspace.wisc.edu/media/iaml+unit+3-9/1_jk95tgms) ~ 9 mins
- [Lecture 10: KNN with Ames](https://mediaspace.wisc.edu/media/iaml+unit+3-10/1_klo7ody6) ~ 12 mins

- [Discussion]() - NOT AVAILABLE FOR 2026
- [Lab](https://mediaspace.wisc.edu/media/Unit+3+Lab+Recording+-+Regression+and+KNN/1_3xk8g050?st=90)


**Lab Materials**

- [Lab](lab/unit_03_ta.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692578) the unit quiz by 8 pm on Wednesday, February 4th.


**Application Assignment**

- clean data: [train](application_assignments/unit_03/ames_train_cln.csv); [validate](application_assignments/unit_03/ames_val_cln.csv); [test](application_assignments/unit_03/ames_test_cln.csv)
- [data dictionary](application_assignments/unit_03/ames_data_dictionary.pdf)
- [lm qmd](application_assignments/unit_03/hw_unit_03_lm.qmd)
- [knn qmd](application_assignments/unit_03/hw_unit_03_knn.qmd)
- solution: [lm](https://dionysus.psych.wisc.edu/iaml/key_unit_03_lm.html); [knn](https://dionysus.psych.wisc.edu/iaml/key_unit_03_knn.html)

- [Submit](https://canvas.wisc.edu/courses/449429/assignments/2579946) the application assignment by 8 pm on Friday, February 6th.

-----

## Unit 4: Introduction to Classification Models 

**Reading**

- @ISL [Chapter 4, pp 129 - 164](pdfs/isl_2.pdf)

**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l04/)
- [Discussion](d04_classification.html)


**Videos**

- [Lecture 1: The Bayes Classifier](https://mediaspace.wisc.edu/media/iaml+unit+4-1/1_5xvs5z3f) ~ 9 mins
- [Lecture 2: Conceptual Overview of Logistic Regression](https://mediaspace.wisc.edu/media/iaml+unit+4-2/1_ut2up1mo) ~ 19 mins
- [Lecture 3: EDA with the Cars Dataset](https://mediaspace.wisc.edu/media/iaml+unit+4-3/1_vydb2j8t) ~ 12 mins
- [Lecture 4: Logistic Regression with Cars Dataset](https://mediaspace.wisc.edu/media/iaml+unit+4-4/1_dzqnsnf0) ~ 32 mins
- [Lecture 5: KNN with Cars Dataset](https://mediaspace.wisc.edu/media/iaml+unit+4-5/1_mj1cyhhj) ~ 19 mins
- [Lecture 6: LDA, DQA, RDA with Cars Dataset](https://mediaspace.wisc.edu/media/iaml+unit+4-6/1_t7mnafsp) ~ 16 mins
- [Lecture 7: Comparisons among Classifiers](https://mediaspace.wisc.edu/media/iaml+unit+4-7/1_tw44we5w) ~ 11 mins

- [Discussion](https://mediaspace.wisc.edu/media/0212.mp4/1_i73y75ad)
- [Lab](https://mediaspace.wisc.edu/media/Unit+4+%282+10+2026%29+-+Classification/1_pf5lqdr7)


**Lab Materials**

- [Lab](lab/unit_04_ta.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692587) the unit quiz by 8 pm on Wednesday, February 11th.

**Application Assignment**
  
- data: [raw](application_assignments/unit_04/titanic_raw.csv); [test](application_assignments/unit_04/titanic_test_cln.csv) 

- [data dictionary](application_assignments/unit_04/titanic_data_dictionary.png) 

- shells: [cleaning EDA qmd](application_assignments/unit_04/hw_unit_04_eda_cleaning.qmd);
[rda qmd](application_assignments/unit_04/hw_unit_04_fit_rda.qmd);
[knn qmd](application_assignments/unit_04/hw_unit_04_fit_knn.qmd) 

- solution: [modeling EDA](https://dionysus.psych.wisc.edu/iaml/key_unit_04_eda_modeling.html); [rda](https://dionysus.psych.wisc.edu/iaml/key_unit_04_fit_rda.html); [knn](https://dionysus.psych.wisc.edu/iaml/key_unit_04_fit_knn.html)

- [Submit](https://canvas.wisc.edu/courses/499807/assignments/2951192) the application assignment by 8 pm on Friday, February 13th.

--------------------------------------------------------------------------------


## Unit 5:  Resampling Methods for Model Selection and Evaluation

**Reading**

- @APM [Chapter 4, pp 61 - 80](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)

- **Supplemental:** @ISL [Chapter 5, pp 197 - 208 186](pdfs/isl_2.pdf)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l05/)
- [Discussion](d05_resample.html)


**Videos**

- [Lecture 1: Overview & Parallel Processing](https://mediaspace.wisc.edu/media/iaml+unit+5-1/1_sv29qmvz) ~ 16 mins
- [Lecture 2: Introduction to Resampling](https://mediaspace.wisc.edu/media/iaml+unit+5-2/1_pyr647gu) ~ 11 mins
- [Lecture 3: Single Validation/Test Set Approach](https://mediaspace.wisc.edu/media/iaml+unit+5-3/1_21l94nvt) ~ 26 mins
- [Lecture 4: Leave One Out Cross Validation](https://mediaspace.wisc.edu/media/iaml+unit+5-4/1_uuaa5nj1) ~ 9 mins 
- [Lecture 5: K-fold Cross Validation Approaches](https://mediaspace.wisc.edu/media/iaml+unit+5-5/1_f60kfk66) ~ 21 mins
- [Lecture 6: Repeated and Grouped K-fold Approaches](https://mediaspace.wisc.edu/media/iaml+unit+5-6/1_a6yo0euq) ~ 11 mins
- [Lecture 7: Bootstrap Resampling](https://mediaspace.wisc.edu/media/iaml+unit+5-7/1_zijywf6b) ~ 11 mins 
- [Lecture 8: Using Resampling to Select Best Model Configurations](https://mediaspace.wisc.edu/media/iaml+unit+5-8/1_0sxcqnj4) ~ 17 mins
- [Lecture 9: Resampling for Both Model Selection and Evaluation](https://mediaspace.wisc.edu/media/iaml+unit+5-9/1_b8abgszd) ~ 11 mins
- [Lecture 10: Nested Resampling](https://mediaspace.wisc.edu/media/iaml+unit+5-10/1_g9jh3461) ~ 14 mins

- [Discussion](https://mediaspace.wisc.edu/media/IAML+2026+0219/1_e2b12t5o)
- [Lab](https://mediaspace.wisc.edu/media/Unit%205%20Lab%20Recording%20-%20Resampling%20Techniques%20and%20Hyperparameter%20Tuning/1_epecb9yw)


**Lab Materials**

- [Lab](lab/unit_05_ta.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692583) the unit quiz by 8 pm on Wednesday, February 18th.

**Application Assignment**

- [data](application_assignments/unit_05/smoking_ema.csv)
- [data dictionary](application_assignments/unit_05/data_dictionary.csv)
- [qmd shell](application_assignments/unit_05/hw_unit_05_resampling.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_05_resampling.html) 

- [Submit](https://canvas.wisc.edu/courses/499807/assignments/2951193) the application assignment by 8 pm on Friday, February 20th.

--------------------------------------------------------------------------------

## Unit 6:  Regularization and Penalized Models

**Reading**

- @ISL [Chapter 6, pp 225 - 267](pdfs/isl_2.pdf)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l06/)
- [Discussion](https://dionysus.psych.wisc.edu/iaml/slides/d06_regularization.html)


**Videos**

- [Lecture 1: An Introduction to Penalized/Regularized Algorithms](https://mediaspace.wisc.edu/media/iaml+unit+6-1/1_dqafjta6) ~ 15 mins
- [Lecture 2: [Intuitions about Penalized Cost Functions and Regularization](https://mediaspace.wisc.edu/media/iaml+unit+6-2/1_uxp8w6am) ~ 11 mins
- [Lecture 3: Ridge Regression](https://mediaspace.wisc.edu/media/iaml+unit+6-3/1_hcghfpo3) ~ 9 mins
- [Lecture 4: LASSO](https://mediaspace.wisc.edu/media/iaml+unit+6-4/1_803c42m3) ~ 8 mins
- [Lecture 5: The Elastic net](https://mediaspace.wisc.edu/media/iaml+unit+6-5/1_r4xy5dws) ~ 4 mins
- [Lecture 6: Emprical Example - Many good predictors](https://mediaspace.wisc.edu/media/iaml+unit+6-6/1_2608sidm) ~ 23 mins
- [Lecture 7: Emprical Example - Good and zero predictors](https://mediaspace.wisc.edu/media/iaml+unit+6-7/1_xmgkkr8t) ~ 9 mins
- [Lecture 8: Emprical Example - LASSO for covariate selection](https://mediaspace.wisc.edu/media/iaml+unit+6-8/1_hlknwl7m) ~ 8 mins


- [Discussion]()
- [Lab](https://mediaspace.wisc.edu/media/Lab+6+Recording%3A+Exercise+%2B+Regularization/1_vwy0vudr)


**Lab Materials**

- [Lab](lab/unit_06_ta.qmd)
- [Attrition Dataset](data/attrition.csv)
- [Concrete Dataset](data/concrete.csv)
- [Lab Exercise Key](lab/unit_06_exercise_key.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692590) the unit quiz by 8 pm on Wednesday, February 25th.

**Application Assignment**

- [data](application_assignments/unit_06/ames_full_cln.csv)
- [data dictionary](application_assignments/unit_06/ames_data_dictionary.pdf)
- [qmd shell](application_assignments/unit_06/hw_unit_06_regularization.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_06_regularization.html) 

- [Submit](https://canvas.wisc.edu/courses/499807/assignments/2951194) the application assignment by 8 pm on Friday, February 27th.

--------------------------------------------------------------------------------

## Unit 8: Advanced Performance Metrics 

**Reading**

- @APM [Chapter 11, pp 247-266](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)
- @APM [Chapter 16, pp 419-435](https://vuquangnguyen2016.files.wordpress.com/2018/03/applied-predictive-modeling-max-kuhn-kjell-johnson_1518.pdf)
- [Wyant et al, in press](./pdfs/wyant_etal_inpress.pdf)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l08/)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d08/)


**Videos**

- [Lecture 1: Unit Introduction](https://mediaspace.wisc.edu/media/iaml+unit+8-1/1_llkkb5j8) ~ 15 mins
- [Lecture 2: The Confusion Matrix, Part 1](https://mediaspace.wisc.edu/media/iaml+unit+8-2/1_nez4aukh)~ 33 mins
- [Lecture 3: The Confusion Matrix, Part 2](https://mediaspace.wisc.edu/media/iaml+unit+8-3/1_r5d4f701)~ 11 mins
- [Lecture 4: The Receiver Operating Characteristic (ROC) Curve](https://mediaspace.wisc.edu/media/iaml+unit+8-4/1_tpe0nzy8) ~ 25 mins
- [Lecture 5: Selecting Model Configurations with Other Metrics](https://mediaspace.wisc.edu/media/iaml+unit+8-5/1_lfyq2h3s) ~ 10 mins
- [Lecture 6: Addressing Class Imbalance](https://mediaspace.wisc.edu/media/iaml+unit+8-6/1_ullvntoe) ~ 24 mins

- [Discussion]()
- [Lab]()


**Lab Materials**

- [Lab](lab/unit_06_lab.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692586) the unit quiz by 8 pm on Wednesday, March 11th.

**Application Assignment**

- [data](application_assignments/unit_08/breast_cancer.csv)
- [qmd shell](https://raw.githubusercontent.com/jjcurtin/book_iaml/main/application_assignments/unit_08/hw_unit_08_performance.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_08_performance.html)

- [Submit](https://canvas.wisc.edu/courses/499807/assignments/2951195) the application assignment by 8pm on Friday, March 13th.

--------------------------------------------------------------------------------

## Unit 9: Decision Trees, Bagging, and Random Forest 

**Reading**

- @ISL [Chapter 8, Tree Based Methods; pp 327 - 352](pdfs/isl_2.pdf)

In addition, much of the content from this unit has been drawn from four chapters in a book called [Hands On Machine Learning In R](https://bradleyboehmke.github.io/HOML/).  It is a great book and I used it heavily (and at times verbatim) b/c it is quite clear in its coverage of these algorithms.  If you want more depth, you might read chapters 9-12 from this book as a supplement to this unit in our course.

**Slide decks**
- [Lecture](https://jjcurtin.quarto.pub/iaml_l09/)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d09/)

**Videos**

- [Lecture 1: Decision Trees](https://mediaspace.wisc.edu/media/iaml+unit+9-1/1_xk3gxr2y) ~ 30 mins
- [Lecture 2: Decision Trees in Ames](https://mediaspace.wisc.edu/media/iaml+unit+9-2/1_nrwshb2s) ~ 20 mins
- [Lecture 3: Bagged Trees](https://mediaspace.wisc.edu/media/iaml+unit+9-3/1_bykr6l2l)i ~ 10 mins
- [Lecture 4: Bagged Trees in Ames](https://mediaspace.wisc.edu/media/iaml+unit+9-4/1_qkn0qrgy) ~ 6 mins
- [Lecture 5: Random Forest](https://mediaspace.wisc.edu/media/iaml+unit+9-5/1_wtuy10yx) ~ 16 mins

- [Discussion]()
- [Lab]()


**Lab Materials**

- [Lab](lab/unit_08_lab.qmd)

**Quiz**

- [Submit](https://canvas.wisc.edu/courses/499807/quizzes/692582) the unit quiz by 8 pm on Wednesday, March 18th.

**Application Assignment**

- [data](application_assignments/unit_09/fifa.csv)
- [qmd shell](application_assignments/unit_09/hw_unit_09_random_forest.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_09_random_forest.html)

- [Submit](https://canvas.wisc.edu/courses/499807/assignments/2951196) the application assignment by 8pm on Friday, March 20th.

## Unit 10: Neural Networks 

**Reading**

- [Neural Networks and Deep Learning, Chapter 1: Using neural networks to recognize handwritten digits](http://neuralnetworksanddeeplearning.com/chap1.html)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l10/)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d10/)

**Videos**

- [Lecture 1: But what is a Neural Network?](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=1&t) ~ 19 mins
- [Lecture 2: Gradient descent, how neural networks learn](https://www.youtube.com/watch?v=IHZwWFHWa-w&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=2&t) ~ 21 mins
- [Lecture 3: What is backpropagation really doing?](https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3&t) ~ 13 mins
- [Optional Lecture 4: Backpropagation calculus](https://www.youtube.com/watch?v=tIeHLnjs5U8&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=4&t) ~ 10 mins
- [Lecture 5: Introduction and the MNIST dataset](https://mediaspace.wisc.edu/media/iaml+10-5/1_uqw3f0o9) ~ 14 mins
- [Lecture 6: Fitting neural networks in tidymodels with Keras](https://mediaspace.wisc.edu/media/iaml+unit+10-6/1_sv7eicou) ~ 18 mins
- [Lecture 7: Addressing overfitting - Intro and L2](https://mediaspace.wisc.edu/media/iaml+unit+10-7/1_ulfnye8s) ~ 5 mins
- [Lecture 8: Addressing overfitting - Dropout](https://mediaspace.wisc.edu/media/iaml+unit+10-8/1_4k4cf1aj) ~ 4 mins
- [Lecture 9: Addressing overfitting - Early stopping](https://mediaspace.wisc.edu/media/iaml+unit+10-9/1_5dlsj34t) ~ 8 mins
- [Lecture 10: Selecting model configurations and final remarks](https://mediaspace.wisc.edu/media/iaml+unit+10-10/1_i448a6ta) ~ 8 mins

- [Discussion]()
- [Lab]()


**Lab Materials**

- [Lab](lab/unit_09_lab.qmd)

**Quiz**

[Submit](https://canvas.wisc.edu/courses/499807/quizzes/692579) the unit quiz by 8 pm on Wednesday, March 25th

**Application Assignment**

- wine quality datasets:  [training](application_assignments/unit_10/wine_quality_trn.csv); [test](application_assignments/unit_10/wine_quality_test.csv)
- [qmd shell](https://raw.githubusercontent.com/jjcurtin/book_iaml/main/application_assignments/unit_10/hw_unit_10_neural_nets.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_10_neural_nets.html)


Submit the application assignment [here](https://canvas.wisc.edu/courses/499807/assignments/2951187) by 8pm on Friday, March 27th

## Unit 11: Explanatory Approaches 

**Reading**

- @Benavoli2017 [paper](pdfs/benavoli_2017_bayesian_t_test.pdf):  Read pages 1-9 that describe the correlated t-test and its limitations.
- @Kruschke2018 [paper](pdfs/kruschke2018a.pdf): Describes Bayesian estimation and the ROPE (generally, not in the context of machine learning and model comparisons)

And these chapters in the book [Interpretable Machine Learning](https://christophm.github.io/interpretable-ml-book/).  They are all short!

- @IML [Chapter 2 - Interpretability](https://christophm.github.io/interpretable-ml-book/interpretability.html)
- @IML [Chapter 3 - Goals of Interpretability](https://christophm.github.io/interpretable-ml-book/goals.html)
- @IML [Chapter 4 - Methods Overview](https://christophm.github.io/interpretable-ml-book/overview.html)
- @IML [Chapter 17 - Shapley Values](https://christophm.github.io/interpretable-ml-book/shapley.html): 
- @IML [Chapter 18 - SHAP](https://christophm.github.io/interpretable-ml-book/shap.html): 
- @IML [Chapter 19 - Partial Dependence Plots](https://christophm.github.io/interpretable-ml-book/pdp.html)
- @IML [Chapter 20 - Accumulated Local Effects (ALE)](https://christophm.github.io/interpretable-ml-book/ale.htmlj)
- @IML [Chapter 21 - Feature Interactions](https://christophm.github.io/interpretable-ml-book/interaction.html)
- @IML [Chapter 23 - Permutation Feature Importance](https://christophm.github.io/interpretable-ml-book/feature-importance.html)


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l11/)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d11/)

**Videos**

- [Introduction to Model Comparisons](https://mediaspace.wisc.edu/media/iaml+unit+11-1a/1_qnvnn5s2) ~ 6 mins
- [An Empirical Example of Feature Ablation](https://mediaspace.wisc.edu/media/iaml+unit+11-1b/1_p15t634g) ~ 13 mins
- [The Nadeau & Bengio Correlated t-test for Model Comparisons](https://mediaspace.wisc.edu/media/iaml+unit+11-2/1_oa94e6ld) ~ 9 mins
- [Bayesian Estimation for Model Comparisons](https://mediaspace.wisc.edu/media/iaml+unit+11-3/1_mvczl7cn) ~ 28 mins
- [Introduction to Feature Importance and the DALEX package](https://mediaspace.wisc.edu/media/iaml+unit+11-4/1_ppfee7t7) ~ 11 mins
- [Permutation Feature Importance](https://mediaspace.wisc.edu/media/iaml+unit+11-5/1_4865nrwv) ~ 7 mins
- [SHAP Feature Importance](https://mediaspace.wisc.edu/media/iaml+unit+11-6/1_oyav56vz) ~ 14 mins
- [Visual Approaches to Understand Models](https://mediaspace.wisc.edu/media/iaml+unit+11-7/1_x5xnumlo) ~ 11 mins

- [Discussion]()
- [Lab]()

**Lab Materials**

- [Lab](lab/unit_10_lab.qmd)

**Quiz**

[Submit](https://canvas.wisc.edu/courses/499807/quizzes/692575) the unit quiz by 8 pm on Wednesday, April 8th

**Application Assignment**

- data: [student_perf_cln.csv](application_assignments/unit_11/student_perf_cln.csv)
- [assignment qmd](https://raw.githubusercontent.com/jjcurtin/book_iaml/main/application_assignments/unit_11/hw_unit_11_explanatory.qmd)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_11_explanatory.html)

Submit the application assignment [here](https://canvas.wisc.edu/courses/499807/assignments/2951189) by 8pm on Friday, April 10th

## Unit 12: NLP 

**Reading**

- @SMLTAR [Chapter 2: Tokenization](https://smltar.com/tokenization.html)
- @SMLTAR [Chapter 5: Word Embeddings](https://smltar.com/embeddings.html)

NOTES: Please read the above chapters more with an eye toward concepts and issues 
rather than code.  I will demonstrate a minimum set of functions to accomplish
the NLP modeling tasks for this unit.

Also know that the entire @SMLTAR [book] is really mandatory reading.  I would also strongly recommend this entire @TMR [book](https://www.tidytextmining.com/).  Both  will be important references at a minimum.


**Slide decks**

- [Lecture](https://jjcurtin.quarto.pub/iaml_l12/)
- [Discussion](https://jjcurtin.quarto.pub/iaml_d12/)

**Videos**

- [Lecture 1: General Text (Pre-) Processing - the stringr package](https://mediaspace.wisc.edu/media/unit_12_lecture_1/1_mq7a05cw) ~ 9 mins
- [Lecture 2: General Text (Pre-) Processing - regular expressions](https://mediaspace.wisc.edu/media/unit_12_lecture_2/1_jijno1uc) ~ 13 mins
- [Lecture 3: The IMDB Reviews Dataset](https://mediaspace.wisc.edu/media/unit_12_lecture_3/1_33gjwtbv) ~ 6 mins
- [Lecture 4: Tokenization- Part 1](https://mediaspace.wisc.edu/media/unit_12_lecture_4/1_ean14ejo) ~ 27 mins
- [Lecture 5: Tokenization- Part 2](https://mediaspace.wisc.edu/media/unit_12_lecture_5/1_z3ywipyc) ~ 13 mins
- [Lecture 6: Stopwords](https://mediaspace.wisc.edu/media/unit_12_lecture_6/1_flyszeb5) ~ 12 mins
- [Lecture 7: Stemming](https://mediaspace.wisc.edu/media/unit_12_lecture_7/1_r8rfzgxy) ~12 mins
- [Lecture 8: Bag of Words](https://mediaspace.wisc.edu/media/unit_12_lecture_8/1_g9hesmnb) ~19 mins
- [Lecture 9: NLP in Action - Part 1](https://mediaspace.wisc.edu/media/unit_12_lecture_9/1_qvb4fkaj) ~ 17 mins
- [Lecture 10: NLP in Action - Part 2](https://mediaspace.wisc.edu/media/unit_12_lecture_10/1_x7jcxtaf) ~ 20 mins

- [Discussion]()
- [Lab]()


**Lab Materials**

- [Lab](lab/unit_11_lab.qmd)

**Quiz**

[Submit](https://canvas.wisc.edu/courses/499807/quizzes/692589) the unit quiz by 8 pm on Wednesday, April 15th

**Application Assignment**

- [data](application_assignments/unit_12/alcohol_tweets.csv)
- [qmd shell](https://raw.githubusercontent.com/jjcurtin/book_iaml/main/application_assignments/unit_12/hw_unit_12_nlp.qmd)
- [GloVE embeddings for twitter](https://dionysus.psych.wisc.edu/iaml/glove_twitter.csv)
- [solution](https://dionysus.psych.wisc.edu/iaml/key_unit_12_nlp.html)

Submit the application assignment [here](https://canvas.wisc.edu/courses/449429/assignments/2579944) by 8pm on Friday, April 17th

## Unit 13: Applications

**Reading**

- @MLY [pdf](pdfs/ng_machine_learning_yearning.pdf)


**Slide decks**

- [Discussion](https://jjcurtin.quarto.pub/iaml_d13/)

**Videos**

No lectures this week.  Only lab and discussion section.

- [Discussion]()
- [Lab]()


**Lab Materials**

- [Lab](lab/unit_12_lab.qmd)

**Quiz**

[Submit](https://canvas.wisc.edu/courses/499807/quizzes/692585) the unit quiz by 8 pm on Wednesday, April 22nd!

**Application Assignment**

No assignment this week!


## Unit 14: Ethics 

**Reading**

- The readings this week will come from @WMD;  We will read the introduction, chapters 1, 3, 5, and the conclusion and afterword sections. A pdf of the book will be shared directly with you.

- We will also read [this article](https://journal.r-project.org/articles/RJ-2022-019/) on emerging methods and tools for assessing model fairness.


**Slide decks**

- [Discussion](https://jjcurtin.quarto.pub/iaml_d14/)

**Videos**

No lectures this week.  Only discussion section.

- [Discussion]()
- [Review]()

**Quiz**

[Submit](https://canvas.wisc.edu/courses/499807/quizzes/692588) the unit quiz by 8 pm on Wednesday, April 29th

**Application Assignment**

No assignment this week!

## References
