# Midterm Exam

## Applications (take-home) Exam

The Applications exam is due at noon on Friday, March 7th.

As the name suggests, it will focus primarily on applications of machine learning. However, within the QMD file there are questions that also assess your understanding of what you are doing and why.

You should complete the exam as you have previously completed the application assignments:

-   Download the datasets and qmd file below
-   Provide the requested code in the empty code chunks that are included in the qmd file
-   Answer the questions posed outside the code chunks within the text sections of the qmd file, immediately after the question.
-   When you are done, knit the file to html and upload this knit file through the Canvas
-   The exam is due on Friday, March 7th, at noon

In contrast to the application assignments, the TAs and I will not be able to answer substantive questions about the exam. However, if you need us to clarify what we are requesting you to do for any specific question or believe you have found an error in the exam, please post your question to the exams channel in Slack and we will respond ASAP

[Exam qmd shell](https://dionysus.psych.wisc.edu/iaml/midterm/midterm.qmd)

Data:

-   [dataset 1](https://dionysus.psych.wisc.edu/iaml/midterm/data/data_1.csv); [data dictionary](https://dionysus.psych.wisc.edu/iaml/midterm/data/data_1_dictionary.docx)
-   [dataset 2](https://dionysus.psych.wisc.edu/iaml/midterm/data/data_2.csv)
-   [dataset 3](https://dionysus.psych.wisc.edu/iaml/midterm/data/data_3.csv)

## Conceptual Exam

The conceptual exam will be held in class during the Discussion section on Thursday, March 6th.

There will be a review session for the conceptual exam in the Lab section on Tuesday, March 4th
