---
editor_options: 
  chunk_output_type: console
---

::: {.content-visible unless-format="revealjs"}
# Final Exams - Applications and Concepts
:::
::: {.content-visible when-format="revealjs"}
# IAML Unit 15: Final Exams - Applications and Concepts 
:::


## Applications (take-home) Exam

The final exam/project consists of two separate questions/analyses.   Please see this [pdf](https://dionysus.psych.wisc.edu/iaml/final/final_exam_25.pdf) for a complete description of the overall requirements and these two separate questions.

You should complete the exam as you have previously completed the application assignments:  

- Download the two datasets that you will use for these two questions

- Provide complete analyses and annotations for the two questions in a series of qmd file (see the specific questions for more details)
  - When you are done, knit the qmd files to html and upload these knit files through the Canvas
  - The exam is due on Friday, May 9th, at noon 

In contrast to the application assignments, the TAs and I will not be able to answer substantive questions about the exam.  However, if you need us to clarify what we are requesting you to do for any specific question or believe you have found an error in the exam, please post your question to the exam channel in Slack and we will respond ASAP

Finally, it is worth noting that we will approach this final exam/project in a manner consistent with the rest of the course - We care most about learning not grades, and so although the final will be of course graded, our goal is for everyone to succeed, and what we're looking for is for people to do their best and to demonstrate what you have learned this semester.  Good luck.

Data:

* [tips.csv](https://dionysus.psych.wisc.edu/iaml/final/tips.csv)
* [airline_passenger_satisfaction.csv](https://dionysus.psych.wisc.edu/iaml/final/airline_passenger_satisfaction.csv)


## Conceptual Exam

The conceptual final exam will be held in our normal classroom during finals week on Tuesday May 6th at 11 am.